namespace ShutkiVorta.Infrastructure.Persistence;

/// <summary>The few SQL constructs that differ between SQLite and SQL Server. Everything else is portable ANSI SQL.</summary>
public interface ISqlDialect
{
    /// <summary>Appends the statement that returns the identity generated by <paramref name="insertSql"/>.</summary>
    string InsertReturningId(string insertSql);

    /// <summary>Appends paging to a query that already ends with ORDER BY. Uses @Skip and @Take parameters.</summary>
    string Page(string orderedSql);
}

internal sealed class SqliteDialect : ISqlDialect
{
    public string InsertReturningId(string insertSql) => $"{insertSql.TrimEnd().TrimEnd(';')}; SELECT last_insert_rowid();";

    public string Page(string orderedSql) => $"{orderedSql} LIMIT @Take OFFSET @Skip";
}

internal sealed class SqlServerDialect : ISqlDialect
{
    public string InsertReturningId(string insertSql) => $"{insertSql.TrimEnd().TrimEnd(';')}; SELECT CAST(SCOPE_IDENTITY() AS INT);";

    public string Page(string orderedSql) => $"{orderedSql} OFFSET @Skip ROWS FETCH NEXT @Take ROWS ONLY";
}
